function Privacy(){

    return(<>
    
     <h1 className="text-center font-semibold text-4xl"> Privacy Policy</h1>

     <p className="text-lg font-medium mx-16 mt-4"> 
Welcome to the ServCrust website www.servcrust.com and ServCrust mobile app operated and owned by ServCrust Pvt. Ltd., a company incorporated under the Companies Act, 2013 having its registered office located at Flat No 207, Aparna Green, Nanakramguda X Road, Gachibowli, Seri Lingampally, K.V Ranga Reddy, Hyderabad -500032, Telangana, (“ServCrust” or “Company” or “we” or “our” or “us”).
    <br/></p>
    <p className="text-lg font-medium mx-16 mt-4"> 
    ServCrust is a digital platform/e-market platform. Its website is available at www.servcrust.com (referred to as “Website”). Any services of the Platform used by the visitors who visit this Website (hereinafter referred to as “you”, “your” or “user”) or your visit/use of this Website is conditioned upon your acceptance of the terms and conditions contained in Terms and Conditions as available on the Website and this Privacy Policy (“Privacy Policy”).
<br/></p>
<p className="text-lg font-medium mx-16 mt-4"> 
This Privacy Policy applies to https://www.servcrust.com/privacypolicy , ServCrust related sites, apps and communications and services (“Services”), including off-site Services such as advertisement services, but excluding services that state that they are offered under a different privacy policy.
<br/></p>
<p className="text-lg font-medium mx-16 mt-4"> 
ServCrust is fully committed to respecting your privacy and want you to understand how we collect, use, and share data about you. This Privacy Policy covers our data collection practices and describes your rights to access, correct, or restrict our use of your personal data. We are committed to protecting it through our compliance with this Privacy Policy. Thus, it is important that you review this privacy policy.
<br/></p>
<p className="text-lg font-medium mx-16 mt-4"> 
This Privacy Policy has been drafted and published in accordance with the Information Technology Act 2000; and the Information Technology (Reasonable Security Practices and Procedures and Sensitive Personal Data or Information) Rules 2011. This Privacy Policy constitutes a legal agreement between you, as a user of the Website and us, as the owner of the Website. You must be a natural person who is at least 18 years of age. You signify that You have read, understood and agree to be bound by this Privacy Policy. If you do not agree with any provisions of this Privacy Policy or the Terms and Conditions, then you may not use/access this Website.
<br/></p>
<p className="text-lg font-medium mx-16 mt-4"> 
<h1 className="text-2xl font-semibold">I. INTRODUCTION</h1>
a) For the purposes of this Privacy Policy, the Capitalised Terms shall have the meaning assigned as below:<br/>
<br/>i. “Act” shall mean the Information Technology Act, 2000 and Rules thereunder as amended from time to time.<br/>
ii. “Information” shall mean and include Personal Information and Sensitive Personal Data and Information as may be collected by ServCrust.<br/>
iii. “Personal Information (PI)” shall have the same meaning as under Rule 2 (i) of the Information Technology (Reasonable security practices and procedures and sensitive personal data or information) Rules, 2011 as amended from time to time.<br/>
iv. “Rules” shall mean the Information Technology (Reasonable security practices and procedures and sensitive personal data or information) Rules, 2011 as amended from time to time.<br/>
v. “Sensitive Personal Data and Information (SPDI)” shall have the same meaning as under Rule 3 of the Information Technology (Reasonable security practices and procedures and sensitive personal data or information) Rules, 2011 as amended from time to time.<br/>
vi. “User/user”, “You/you”, “Your/your” means any person, user, Registered User, viewer or Registered Customer who views, browses, accesses or uses our Platform;<br/>
vii. “Use” or “Using” means to browse, access, view, copy, availing Services or other benefit from using the Platform;<br/>
viii. “Customer” means a User who has or is willing to obtain the Services of website, mobile application or any other platform of ServCrust.<br/>
ix. “Services” means all the services as provided in the Terms & Conditions from time to time.<br/>
x. “Website” or “ServCrust Websites” means and includes www.servcrust.com and ServCrust mobile app accessed through or downloaded from the app store i.e., Android or IOS, which might be used or accessed at any other platform where the Website can be accessed from on mobile phones and such other devices, like, mobile application (whether or not on Android or IOS) or any other platform as provided by ServCrust.<br/>
<br/>b) Users' correspondence, transactions/offers or related activities with third parties, including but not limited to payment providers, logistics providers and verification service providers, are solely between the User and that third party.
<br/>c) By providing us with your Personal Information you expressly consent to us processing your Personal Information in accordance with the terms of this Privacy Policy.
<br/></p>
<p className="text-lg font-medium mx-16 mt-4"> 
<h1 className="text-2xl font-semibold">II. CHANGES TO THE PRIVACY POLICY</h1>
We may update our Privacy Policy from time to time. Thus, you are advised to review this page periodically for any changes. We will notify you of any changes by posting the new Privacy Policy on this page. These changes are effective immediately after they are posted on this page. If we make changes to this Privacy Policy, including a material change in the way we use your Personal Information, it will be deemed to be notified to and read and agreed by you on your using the Website and/or related Services once we post the same on our Website. Your continued usage will constitute express consent to us continuing to process your Personal Information in accordance with the terms of our revised policy. Last update date:June/01/2023.
<br/></p>
<p className="text-lg font-medium mx-16 mt-4"> 
<h1 className="text-2xl font-semibold">III. WHAT DATA DO WE COLLECT</h1>
We collect the following data from the Users in the manner stated in this Privacy Policy:<br/>
<br/>a) Upon registration on our Website, for the purpose of creation of profile, personally identifiable information such as your name, location, email address, phone number, date of birth, employment status, gender, profile picture, sexual orientation, language and/or other similar information is collected from you.
<br/>b) Upon registration on our Website, for the purpose of creation of profile, you may choose to additionally provide information such as your preferred language, professional details, description of self, relationship status, access to information on your device to optimize your use and access of Services. However, such access granted to the Application may can be restricted from the device settings.
<br/>c) Date and time of your visit on our Website along with the navigation details such as webpages visited and time spent on each webpage, and the details of the referring site.
<br/>d) Data regarding your device such as the type of device, type of operating system, type of web browser, and IP (internet protocol) address is collected.
<br/>e) Account details: these include your username and password and preferred account settings such as the language and time zone etc.
<br/>f) If you choose to post messages on our message boards, chat rooms or other message areas or leave feedback, we will collect and store such information you provide to us. We retain this information as necessary to resolve disputes, provide customer support, respond to queries and inquires, and troubleshoot problems and improve the Services.
<br/>g) The call facility provided by ServCrust for customer support can be recorded for quality control checks to provide better service to the customers, as evidence and for any other purpose as mandated by the law.
<br/>h) Information from Service use: we log usage data when you visit or otherwise use our Services, including our sites and app; the types of content you view or engage with; users you follow on the Application, users who follow you on the Application\the features you use; users who send you chat requests and have chatted with you; the unique device identifier on the Application; the language; the actions you take; install or update our mobile apps, device information, the people or accounts you interact with; and the time, frequency and duration of your activities on our Website along with the navigation details such as webpages visited and time spent on each webpage, and the details of the referring site.
<br/>i) Surveys: Finally, we may collect additional information from or about you in other ways, including but not limited to, when you provide feedback(s), modify your content or email preferences, respond to surveys, provide comments, or communicate with us. Such information may include your name, email address, mobile number, location, etc and only such information that you may specifically choose to provide us.
<br/>j) Any personally identifiable information provided by you will not be considered as sensitive if it is freely available and / or accessible in the public domain like any comments, messages, blogs, scribbles available on social platforms like Facebook, Twitter, Instagram, etc.
<br/>k) By installing the ServCrust application on a compatible Android or iOS smartphone, with your consent ServCrust shall have access to making phone calls, SMS, instant messages, contacts, Internet, your network state, your device location, camera, files and media, internal device storage and other permissions required to provide our service offerings. Your access to ServCrust products/services may be affected in the event your consent is not provide for the aforementioned permissions. We may also collect the precise location of your device when the application is running in the foreground or background. We may also derive your approximate location from your IP address. We may use this information to provide you with location-based services including but not limited to search results and other personalized content.
<br/>l) Data collected from the Merchants: Company name, address, nature of business, email, phone number, GST number, contact details.
<br/>m) Customer Data: We shall collect the name, contact number and delivery GPS location.
<br/>n) In our efforts to continually improve our product and service offerings, we and our affiliates collect and analyse demographic and profile data about our users' activity on our Platform.
<br/>o) Data available in public domain or received from any third party including social media channels, including but not limited to personal or non-personal information from your linked social media channels (like name, email address, friend list, profile pictures or any other information that is permitted to be received as per your account settings) as a part of your account information.
<br/></p>
<p className="text-lg font-medium mx-16 mt-4"> 
<h1 className="text-2xl font-semibold" >IV. HOW DO WE COLLECT YOUR DATA</h1>
We collect the data in the following manner: <br />
<br />a) Through Google Analytics:
<br />i. We use a third-party JavaScript plug-in provided by Google Inc. called "Google Analytics" to provide us with useful traffic statistics and to better understand how you use our Website. We do not have direct access to the information obtained from Google Analytics, but Google provides us with a summary through their dashboard.
<br />ii. Google does not provide us with direct access to your Personal Information and therefore we cannot see this information.
<br />iii. We may share the information obtained from Google Analytics with business partners who are interested in advertising on our website. The information shared with these business partners will not contain any Personal Information.
<br />iv. You can opt-out of having your information collected by Google Analytics by downloading the Google Analytics opt-out browser add-on provided by Google. This will prevent your information being used by Google Analytics. Doing this will not affect your ability to use our Website in any way. We also honour the Do Not Track header and will not track visitors who have Do Not Track switched on.
<br />b) Information collected by third-party: We may collect information about you from thirdparty sources, including but not limited to, the following channels:
<br />i. public databases;
<br />ii. marketing partners and resellers;
<br />iii. advertising partners and analytics providers.
<br />c) Automatic collection by ServCrust: Most of the PI or SDPI that we collect is directly provided by you. In the following situations, we will collect and process the information about you:
<br />i. Where you register yourself on the Platform as a user. We collect and store your personal information you voluntarily provide such as name, email address, phone number, gender, geographical information such as city, linguistic compatibility, and other information such as education qualifications, work experience etc. as may be collected at the time of registration on the Website.
<br />ii. where you log in or visit ServCrust, or opt to use any such Services of ServCrust, which is available only to registered users.
<br />iii. where you provide information regarding yourself when you make an enquiry through the enquiry form
<br />iv. where you provide PI/SDPI directly to ServCrust over telephone. ServCrust may make and keep a record of such information shared by you.
<br />v. where you voluntarily complete any user survey or provide feedback to us via email or any other channel.
<br />vi. where you provide Personal Information to in physical form whether sent through post or courier or handed over to a ServCrust representative in person.
<br />vii. other situations where we may automatically collect your information as mentioned in this Privacy Policy or our Terms & Conditions.
<br />d) Social media Login
<br />i. If you register or log into your account through a third-party social media service such as Google or any other social media login that we may allow in future, we shall have access to some of your third-party account information from such third party social media service, such as your name and other information including information regarding your network in that account, as permitted by that service. You have the ability to disable the connection between our Website and/or the Mobile App and third-party account at any time.
<br />ii. By using Google or any other social login we may allow in the future, you adhere to our Privacy Policy and Terms, as well as the privacy policies and terms of service of Google and other social media sites. Please read the terms of service and privacy policy for any social media login you might be using to understand how data is collected and used.
<br/></p>
<p className="text-lg font-medium mx-16 mt-4"> 
<h1 className="text-2xl font-semibold" >V. HOW WE USE THE INFORMATION WE COLLECT</h1>
We use the information we collect about you for the following purposes or in the following manner: <br />
 <br />a) To provide and maintain ServCrust’ Services: We use the information collected from you to provide, support, personalize, maintain, deliver, provide and develop our Services (including but not limited to processing transactions, communicating with the users) and verify users' identities. How we use your personal information will depend on which Services you use, how you use those Services and the choices you make in your Settings. We use the information we have about you to provide and personalize our Services, including with the help of automated systems and inferences we make, so that our Services can be more relevant and useful to you and others. We use the IP address and unique identifiers stored in your device's cookies to help us authenticate your identity and activities and provide services. Given our legal obligations and system requirements, we cannot provide you with all or some of our services without data like identification information, supervision information, service usage information, communication information, and transaction information.
 <br />b) To protect our users: We use the information collected to protect our Platform, users' accounts, and archives. In some cases, we may also have a legal obligation to collect Personal Information from you or may otherwise need the Personal Information to protect your vital interests or those of another person. We use IP addresses and cookies to protect against automated abuse such as spam, phishing, and Distributed Denial of Service (DDoS) attacks. Further, we analyse browsing activities with the goal of detecting suspicious behaviours as early as possible to prevent potential fraud and loss of funds to bad actors.
 <br />c) For other business purpose: By registering on the Website, you give us your express consent to receive promotional emails about our Services and emails announcing changes to, and new features on, the Website. If at any time, you decide that you do not wish to receive any such emails, you can opt out of receiving such emails. Additionally, we do use comments made by you about the Website for marketing purposes and by making such comments you expressly consent to our using such comments for marketing purposes.
 <br />d) ServCrust will share some or all of your Information with another business entity should we (or our assets) plan to merge with or be acquired by that business entity. Should such a transaction occur then the other business entity (or the new combined entity) will be required to follow this privacy policy with respect to your Information.
 <br />e) Legal obligation: We may need to disclose your Information to law enforcement agencies, government agencies or other third parties where we are compelled so to do by court order or similar legal procedure; where we are required to disclose your Information to comply with law; where we are cooperating with an ongoing law enforcement investigation or where we have a good faith belief that our disclosure of your Information is necessary to prevent physical harm or financial loss, to report suspected illegal activity or to investigate a possible violation of our Terms and Conditions.
 <br />f) We do not sell or rent any of your Information to third parties in the normal course of doing business and will only share your Information with third parties in accordance with this Privacy Policy.
<br/></p>
<p className="text-lg font-medium mx-16 mt-4"> 
<h1 className="text-2xl font-semibold" >VI. COOKIES</h1>
<br />a) What Are Cookies? Cookies are small amounts of data that are sent to your browser and stored on your computer's hard drive to collect standard internet log information and visitor behaviour information. When you visit our Website, we can automatically collect information from you through cookies or similar technologies. For more information, please visit: https://en.wikipedia.org/wiki/HTTP_cookie <br />
<br />b) How Do We Use Cookies? We use cookies in a range of ways to make your experience on our Website more enjoyable, including but not limited to:<br />
<br />i. Authentication: We use cookies to verify your account and determine when you’re logged in so that we can make it easier for you to access the ServCrust Services and show you the appropriate experience and features. If you’re signed into ServCrust, Cookies help s show you the right information and personalize your experience in line with your settings;
<br />ii. Security: We use cookies to help us keep your account and information safe and secure and help us detect any malicious activity and violations when you visit our Services.
<br />iii. Preferences, features and Services: We use cookies to enable the functionality of our Services, and provide you with features, insights and customized content. We also use these technologies to remember information about your browser and your preferences;
<br />iv. Advertising, recommendations, insights and measurement: We use cookies to record our performance and verify the effectiveness of online advertising through third-party services with cookies.
<br />c) What Types of Cookies Do We Use? We use different types of cookies, including but not limited to: <br />
<br />i. Functional Cookies: We use such cookies to help us identify you and remember your previous preferences and settings, which may include your device, your operating system, your preferred language, your location, and other session data. We use a mix of first-party and third-party cookies. We use Cookies to improve your experience of Services.
<br />ii. Targeting Cookies: We use these cookies to collect information about your visit to our Website, the content you view, the links you follow, and other information about your browsers, devices, your IP addresses and referral URLs. These Cookies may be set through our site by our advertising partners and maybe used by them to build a profile of your interests and show your relevant advertisements on their websites. This means that when you visit another website, you may also be shown advertisements based on your browsing patterns on ServCrust. If you do not allow these Cookies, you will experience less targeted advertisement.
<br />iii. Necessary Cookies: Such Cookies are necessary for our Website to function and are usually set in response to actions made by you which amount to a request for Services, such as setting your privacy preferences, logging in or filling in forms. These Cookies do not store any personal identifiable information and cannot be stitched off in your systems.
<br />iv. Performance Cookies: We use these Cookies to determine and measure the performance of our Website. We use these Cookies to understand and improve our features and Services, including as you navigate through our Website or when you access ServCrust from other websites, applications or devices.
<br />d) How to Manage Cookies? Most browsers are pre-set to accept cookies. Where required, you can adjust your browser setting to prevent cookies or to notify you as soon as cookies are loaded. We enable you to reject the use of certain cookies for purposes such as advertising, by visiting your cookie settings, without affecting the lawfulness of processing based on your consent before its withdrawal. You can change your preferences at any time by visiting settings. However, stopping all cookies might mean that you cannot access or use some features of ServCrust.<br />
<br/></p>
<p className="text-lg font-medium mx-16 mt-4"> 
<h1 className="text-2xl font-semibold" >VII. LINKS TO THIRD PARTY SITES</h1>
<br />a) We may provide links of other websites of interest on the Website, without any accuracy, completeness, or usefulness of any content, warranty, merchantability, endorsement, suitability, any assurance of quality, authenticity, and appropriateness to view such websites and responsibility, liability, obligations on part of the Website. This Policy does not apply when you access such sites or links.
<br />b) These third-party websites may use technology to send the advertisements that appear on the Website directly to User. ServCrust does not have access to or control over the cookies or other features that such third-party websites may use, and the information practices of these third-party websites are not covered by this Policy. Therefore, ServCrust cannot be held responsible for the protection and privacy of any information which User provides whilst visiting such websites of interest. Users shall contact them directly for more information about their privacy practices.
<br />c) Any opinions, advice, statements, services, offers, or other information or content expressed or made available by third parties, including information providers, or any other Users are those of the respective author(s) or distributors and not of the ServCrust
<br/></p>
<p className="text-lg font-medium mx-16 mt-4"> 
    <h1 className="text-2xl font-semibold" >VIII. SECURITY & STORAGE OF YOUR INFORMATION</h1>
   <br /> a) We hold your Personal Information on secure servers. By providing us with Personal Information, you consent to the transfer of your Personal Information to, and its storage on, our secure servers. We take every precaution to safeguard all your Personal Information from unauthorized access, use or disclosure. However, the internet is not a secure medium and we cannot guarantee the privacy of your Personal Information.
i. You must enter your username and password each time you want to access your account or make transactions on the Website.
ii. Choose your password carefully using unique numbers, letters and special characters. Never share your username and password with anyone.
iii. If you are concerned that your username or password has been compromised, please contact our customer support team immediately and ensure you change your password by logging onto the user settings section of the Website.
<br />b) The information provided by the user is stored in access-controlled facilities with restricted access. Personal Information transmitted over the internet is protected through the use of encryption, using the Secure Socket Layer (SSL) or equivalent protocols.
<br />c) We shall use generally accepted industry standards to protect the Personal Information submitted to us, both during transmission and upon receipt. However, please be advised that no method of transmission over the internet, or method of electronic storage, is 100% secure. Therefore, even though we strive to use commercially acceptable means to protect your Personal Information, we cannot guarantee its absolute security and your use of the Website is at your sole risk and discretion. We also cannot warrant that such Personal Information may not be misused in the event our safeguards and protocols are breached by a malicious third-party. Further, we are not liable to nor can we fully control the actions of other users with whom you may choose to share your information.
<br />d) You agree that, all intellectual property including but not limited to copyright, trademark, any personal information, content, photographs, images, experience sharing, feedback, opinions that is voluntarily shared by you with us or uploaded on the Website do not infringe any rights of third parties in any manner and you give us unrestricted, perpetual right of use of such intellectual property for any purpose whatsoever.
<br />e) It is the responsibility of the user to keep the password confidential. You have to ensure that you always log out, before sharing the device with a third party and it is advised that the user utilize a service to protect access to the user’s device.
<br />f) The collection, usage, and sharing of user information by us shall be in compliance with the Information Technology (Reasonable Security Practices and Procedures and Sensitive Personal Data or Information) Rules, 2011 and other applicable laws.
<br/></p>
<p className="text-lg font-medium mx-16 mt-4"> 
    <h1 className="text-2xl font-semibold" >IX. DISCLOSURE AND SHARING OF INFORMATION</h1>
    <br />a) Where PI/SPDI is required to be shared, arising out of any contractual obligation, ServCrust shall part with such PI/SPDI only in accordance with your consent for the same. To the extent necessary to provide you the requested Services or to the extent required under applicable law, we may provide your PI/SPDI to the following Third Parties without notice to you:
i. Consultants (including auditors, authorized vendors) on a ‘need to know’ basis under a Non-Disclosure Agreement;
ii. Governmental authorities, in such manner as permitted or required by applicable law;
<br />b) All employees of ServCrust have been selected in accordance with our strict security policies and practices and are bound by confidentiality obligations. ServCrust’ employees are subject to stern disciplinary action, including termination, civil liability, and criminal prosecution, if they fail to meet any of these obligations, as stated.
<br />c) ServCrust may also use third party vendors or service providers to help us provide services to you, such as courier services, operating the payment gateway functionality of the website, tailoring services with the help of boutiques, tailors, cloth stores, etc. Such third parties are required to maintain the confidentiality of the information we provide to them under contract and under law.
<br />d) ServCrust, its group, affiliate and subsidiary companies may, in compliance with applicable laws, share/transfer/assign all of your Personal Information and other information with any other business entity(ies), in the event of a merger, sale, reorganization, amalgamation, joint ventures, assignment, restructuring of business or transfer or disposition of all or any portion of the business.
<br /><br/></p>
<p className="text-lg font-medium mx-16 mt-4"> 
    <h1 className="text-2xl font-semibold" >X. AGREEMENT</h1>
    This Policy along with the Terms & Conditions and any other relevant policies or disclosures contains the entire understanding and agreement between the User and the Website and supersedes any and all prior understandings relating to the Website. This Policy cannot be changed or terminated orally. If any provision of this Policy is held to be illegal, invalid or unenforceable, this will not affect any other provisions and the Policy will be deemed amended to the extent necessary. Any provision which must survive in order to allow us to enforce its meaning, shall survive the termination of this Policy. This Policy should at all times be read along with the Terms & Conditions and any other policies of the Website.
<br/></p>
<p className="text-lg font-medium mx-16 mt-4"> 
    <h1 className="text-2xl font-semibold" >XI. RETENTION AND REVOCATION OF INFORMATION</h1>
<br/>a) We shall retain the records as per applicable laws and such other statutory / regulatory requirements from time to time. In the event any legal / regulatory proceeding is pending, we can retain records for a longer period. We shall store the data/ information/ records on a server owned by ServCrust, its group, affiliate or subsidiary companies in India.
<br/>b) We may keep our records of the electronic instructions/transactions in any form as permitted under Applicable law. In this regard, all records, whether in electronic form, magnetic form, documents or any other form with respect to electronic instructions/ online transactions shall be conclusive evidence of such instructions/ transactions and shall be binding on the User.
<br/>c) We shall retain your personal data till the period necessary or for longer periods of time for providing any relevant activities or services or for the purpose of any regulatory, tax and accounting requirements.
<br/>d) Please note: Even after your account is terminated, we retain your transactional data for as long as we have a legitimate purpose to do so (and in accordance with applicable law), including to assist with legal obligations, resolve disputes, and enforce our agreements. We may retain and disclose such data pursuant to this Privacy Policy after your account has been terminated.
<br/>e) In the event, you wish to no longer avail our Services or intend to request that ServCrust no longer retain your PI/SPDI or where you intend to modify the current PI/SPDI, you may contact ServCrust as provided herein below.
<br/></p>
<p className="text-lg font-medium mx-16 mt-4"> 
    <h1 className="text-2xl font-semibold" >XII. MISCELLANEOUS</h1>
    A. Managing Local Shared Objects A local shared object is like most other browser cookies except that it can store additional types of information. These cookies cannot be controlled using the mechanisms listed above. Our Website uses these types of cookies to store user preferences for media player functionality and without them some video content may not play properly.
B. Social Buttons The Website contains 'social buttons' to enable users to share or bookmark web pages. These are buttons for third party social media sites and these sites may log information about your activities on the Internet including on this Website. Please review the respective terms of use and privacy policies of these sites to understand exactly how they use your information.
C. External Web Services The Company sometimes uses external web services on this Website to display content within the web pages of this Website, for example to display images, show videos or run polls. As with the social buttons, the Company cannot prevent these sites or external domains, from collecting information on your use of this embedded content.
<br/></p>

    <p className="text-lg font-medium mx-16 mt-4"> 
    <h1 className="text-2xl font-semibold" >XIII. CONTACTING US</h1>
   <br /> a) For questions related to updating or changing your account information or any other Information provided by you and for Your valuable feedback regarding this Policy, please send an e-mail to wecare@servcrust.com
   <br /> b) Further, for time-bound and speedy redressal of any discrepancies and grievances in relation to Personal Information provided, please feel free to reach out to our Grievance Officer at wecare@servcrust.co
<br/></p>

    </>)
}

export default Privacy